---
title: "Spatial Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Spatial analysis

```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(scales)
library(leaflet)
library(ggmap)

```

```{r}
ak_regions <- read_sf("shapefile_demo_data/ak_regions_simp.shp")

class(ak_regions)

plot(ak_regions)
#projection is bad due to alutian chain
#st_crs tells us the corrdinate reference system
st_crs(ak_regions)
#link in lesson to all epsg codes or use epsg.io to look up codes

```

```{r}
#tranfsorm to different coordinate system
ak_regions_3338 <- ak_regions %>% st_transform(crs = 3338) 

plot(ak_regions_3338)
#this tranformation put the alutians back where they are supposed to be

summary(ak_regions_3338)
```

# read in population csv
```{r}
pop <- read.csv("shapefile_demo_data/alaska_population.csv", stringsAsFactors = F)

class(pop)

#set of special functions under ?st_join
```


```{r}
pop_4326 <- st_as_sf(pop, coords = c('lng', 'lat'),
                     crs = 4326, 
                     remove = F)
#remove = false to keep the coordinate data
```

```{r}
pop_3338 <- pop_4326 %>% st_transform(crs = 3338)
```


```{r}
pop_joined <- st_join(pop_3338, ak_regions_3338, join = st_within)
```

```{r}
pop_region <- pop_joined %>% 
  as.data.frame() %>% 
  group_by(region) %>% 
  summarise(total_pop = sum(population)) 

# run ?sf::tidyverse for help on tidyverse operations

```

```{r}
# sf operation with both pop and region information
pop_region_3338 <- left_join(ak_regions_3338, pop_region)

plot(pop_region_3338)
```

```{r}
#what does the pop look like by mnmgt area?
pop_mgmt_3338 <- pop_region_3338 %>% 
  group_by(mgmt_area) %>% 
  summarise(total_pop = sum(total_pop), do_union = F)
#the do union = false kept mgmt areas ( = T would dissolve internal mgmt boundaries)

plot(pop_mgmt_3338["total_pop"])
```

#How to write a file out to disk
```{r}
write_sf(pop_region_3338, "shapefile_demo_data/ak_region_population.shp",
         delete_layer = T)
```
# make maps
```{r}
ggplot(pop_region_3338) +
  geom_sf(mapping = aes(fill = total_pop)) +
  theme_bw() +
  labs(fill = "Total Population") +
  scale_fill_continuous(low = "khaki", high = "firebrick", labels = scales::comma)

```

# book shows how to add other layer to our working map (like rivers and points ect)

```{r}
rivers_3338 <- read_sf("shapefile_demo_data//ak_rivers_simp.shp")

```

```{r}
ggplot() +
  geom_sf(data = pop_region_3338, aes(fill = total_pop)) +
  geom_sf(data = rivers_3338, aes(size = StrOrder), color = "black") +
  geom_sf(data = pop_3338, aes(), size = .5) +
  scale_size(range = c(0.01, 0.2), guide = F) +
  theme_bw() +
  labs(fill = "Total Population") +
  scale_fill_continuous(low = "khaki", high =  "firebrick", labels = comma)

```

```{r}
pop_3857 <- pop_3338 %>%
  st_transform(crs = 3857)

```

```{r}
# Define a function to fix the bbox to be in EPSG:3857
# See https://github.com/dkahle/ggmap/issues/160#issuecomment-397055208
ggmap_bbox_to_3857 <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}
#code above here in this box is necessary for all applications

```

```{r}
bbox <- c(-170, 52, -130, 64)   # This is roughly southern Alaska
ak_map <- get_stamenmap(bbox, zoom = 4)
ak_map_3857 <- ggmap_bbox_to_3857(ak_map)
```

```{r}
ggmap(ak_map_3857) + 
  geom_sf(data = pop_3857, aes(color = population), inherit.aes = F) +
  scale_color_continuous(low = "khaki", high =  "firebrick", labels = comma)
```


# There is more in the lesson below this point that is not covered in this 